Task #8 Add log info
Delvin09/CoolTest_FW pull request #18
Opened 2024-01-03 02:36 UTC by tratatun

2024-01-03 08:41 UTC, Delvin09 requested changes

2024-01-03 08:41 UTC, Delvin09 commented on CoolTest.Core/Logger/ILogger.cs
> +    public interface ILogger
достаточно такого, я думаю:
```
        public void LogInfo(string message);

        public void LogWarning(string message);

        public void LogError(Exception ex);
```

2024-01-03 08:41 UTC, Delvin09 commented on CoolTest.Core/Logger/ILogger.cs
> +    public interface ILogger
думаю интерфейс лучше вынести в проект с абстракциями

2024-01-03 08:41 UTC, Delvin09 commented on CoolTest.Core/TestEngine.cs
> +        private ILogger _logger { get; set; }
я бы убрал сеттер

2024-01-03 08:41 UTC, Delvin09 commented on CoolTest.Core/TestEngine.cs
> +                        _logger.LogInfo($"Run tests for test group {group}");
я бы еще добавил LogInfo после работы тестов

2024-01-03 08:41 UTC, Delvin09 commented on CoolTest.Core/Test.cs
>              catch (Exception ex)
я бы еще добавил LogInfo до и после работы теста

2024-01-03 08:41 UTC, Delvin09 commented on CoolTest.Core/Test.cs
> +        private ILogger _logger { get; set; }
я бы убрал сеттер

2024-01-03 08:41 UTC, Delvin09 commented on CoolTest.Core/Logger/Logger.cs
> +    public class Logger : ILogger
переименуй в ConsoleLogger

2024-01-03 08:41 UTC, Delvin09 commented on CoolTest.Core/TestGroup.cs
> +        private readonly ILogger _logger;
поля переноси вверх, до конструктора и свойств.

2024-01-03 08:41 UTC, Delvin09 commented on CoolTest.Core/Test.cs
> +        private ILogger _logger { get; set; }
или сделал бы риlонли полем, как в TestGroup

2024-01-03 08:41 UTC, Delvin09 commented on CoolTest.Core/TestGroup.cs
> +                    _logger.LogWarning(new InvalidOperationException("Can't create the object of test class!"));
1. Логгер не должен убирать исключение
2. Ты должен тут его (исключение) просто залоггировать

2024-01-03 08:41 UTC, Delvin09 commented on CoolTest.Core/TestGroup.cs
> +                    _logger.LogWarning(new InvalidOperationException("Can't create the object of test class!"));
3. Я бы еще залогировал как инфу, что вообще происходит (до начала вызова тестов, перед и после каждого и т.д.)

2024-01-03 08:41 UTC, Delvin09 commented on CoolTest.Core/TestProvider.cs
> +        public TestProvider(string assemblyPath, ILogger logger)
Я бы еще добавил логгирование тут:
1. Для создания и диспоуса контекста загрузки сборки
2. Для резолва сборок (обработчик события)
3. Для получения списка тестов.

2024-01-03 15:46 UTC, Delvin09 requested changes

2024-01-03 15:46 UTC, Delvin09 commented on CoolTest.Core/TestEngine.cs
> +            _logger = new Logger.Logger();
пускай логгер приходит в TestEngine

2024-01-04 03:12 UTC, tratatun commented on CoolTest.Core/Logger/Logger.cs
> +    public class Logger : ILogger
в следующей таске, как я понимаю, его буду дополнять функциональностью записи в файл? или это будет отдельный логгер?

2024-01-04 03:59 UTC, tratatun commented on CoolTest.Core/TestProvider.cs
> +        public TestProvider(string assemblyPath, ILogger logger)
готово

2024-01-04 04:06 UTC, tratatun commented on CoolTest.Core/TestGroup.cs
> +                    _logger.LogWarning(new InvalidOperationException("Can't create the object of test class!"));
вроде все добавил. Или еще где-то?

2024-01-04 09:37 UTC, Delvin09 approved these changes, later dismissed
Синхронизуй свою ветку с мастером, а потом можешь мержить ПР

2024-01-04 09:37 UTC, Delvin09 commented on CoolTest.Core/Logger/Logger.cs
> +    public class Logger : ILogger
Хм, хороший вопрос. Я думаю мы должны сделать чуть сложнее.
Пусть пока будет так)

2024-01-04 19:23 UTC, tratatun commented
@Delvin09 синхронизировал, нужен аппрув опять

2024-01-04 20:05 UTC, Delvin09 approved these changes

2024-01-04 20:07 UTC, merged