Add Before/After test result
Delvin09/CoolTest_FW pull request #22
Opened 2024-01-10 22:09 UTC by Jyugo009

2024-01-11 10:48 UTC, Delvin09 requested changes

2024-01-11 10:48 UTC, Delvin09 commented on CoolTest.Core/TestEngine.cs
> +        public delegate void BeforeTestEventHandler(object sender, TestEventArgs e);
используй EventHandler<T>

2024-01-11 10:48 UTC, Delvin09 commented on CoolTest.Core/TestEngine.cs
> +        public class TestEventArgs : EventArgs
Вынеси все EventArgs в сборку CoolTest.Abstarctions

2024-01-11 10:48 UTC, Delvin09 commented on CoolTest.Core/TestEngine.cs
> +            public string AssemblyName { get; set; }
убери сеттеры из свойств, и добавь конструктор для их инициализации

2024-01-11 10:48 UTC, Delvin09 commented on CoolTest.Core/TestEngine.cs
> +        public event BeforeTestEventHandler BeforeTest;
BeforeTestEventHandler?
AfterTestEventHandler?

2024-01-11 10:48 UTC, Delvin09 commented on CoolTest.Core/Test.cs
> +        private readonly TestEngine _testEngine;
не думаю, что класс Test должен знать про TestEngine.
лучше сделать пару таких же событий или тут (Test) или в TestGroup, а в TestEngine подписаться на них и просто пробросить в собития TestEngine

2024-01-11 10:48 UTC, Delvin09 commented on CoolTest.Core/TestProvider.cs
> +                                .Select(m => new Test(m.GetCustomAttribute<TestAttribute>()?.Name ?? m.Name, m, _logger, _assembly?.GetName()?.ToString(), t.Name))
assemblyName по идее можно получить из MethodInfo

2024-01-11 21:22 UTC, Jyugo009 commented on CoolTest.Core/TestEngine.cs
> +        public delegate void BeforeTestEventHandler(object sender, TestEventArgs e);
+

2024-01-11 21:23 UTC, Jyugo009 commented on CoolTest.Core/TestEngine.cs
> +            public string AssemblyName { get; set; }
+

2024-01-11 21:23 UTC, Jyugo009 commented on CoolTest.Core/TestEngine.cs
> +        public event BeforeTestEventHandler BeforeTest;
+

2024-01-17 23:24 UTC, Jyugo009 commented on CoolTest.Core/TestEngine.cs
> +        public class TestEventArgs : EventArgs
+

2024-01-18 01:33 UTC, Jyugo009 commented on CoolTest.Core/Test.cs
> +        private readonly TestEngine _testEngine;
+

2024-01-18 09:15 UTC, Delvin09 approved these changes
Я чуть поправил код, посмотри. И можно мержить. Сначала синхронизируй свою ветку с мастером (смержи в свою ветку мастер).

2024-01-18 09:16 UTC, Delvin09 approved these changes, later dismissed

2024-01-19 09:32 UTC, Delvin09 approved these changes

2024-01-19 15:45 UTC, merged